// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qitkbdbdqdutylfsctaf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpdGtiZGJkcWR1dHlsZnNjdGFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxOTYxNzQsImV4cCI6MjA2NTc3MjE3NH0.q3TcatEVMZoG47Qe2q6npXCdlNpUKhKaQSImQUinVNg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);